language: java
install: true
dist: trusty
jdk:
  - openjdk13
env:
  global:
    - JAVA8_HOME=/usr/lib/jvm/java-8-openjdk-amd64
branches:
  only:
  - master
script:
  - ./gradlew --continue clean build -s -p modules/  
  
deploy:
  provider: heroku
  api_key:
    secure: d41656cb-59c3-4d2e-8343-3dbddd54a44c